scorbot:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Arm's joints controllers
  
  base_position_controller:
    type: position_controllers/JointPositionController
    joint: base

  shoulder_position_controller:
    type: position_controllers/JointPositionController
    joint: shoulder
  
  elbow_position_controller:
    type: position_controllers/JointPositionController
    joint: elbow

  pitch_position_controller:
    type: position_controllers/JointPositionController
    joint: pitch

  roll_position_controller:
    type: position_controllers/JointPositionController
    joint: roll

  right_finger_position_controller:
    type: position_controllers/JointPositionController
    joint: right_finger_tras

  left_finger_position_controller:
    type: position_controllers/JointPositionController
    joint: left_finger_tras

