scorbot:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Arm controller
  scorbot_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - base
      - shoulder
      - elbow
      - pitch
      - roll
      - right_finger_tras
      - left_finger_tras

