joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Joints controllers, each joint with individual command
base_controller:
  type: position_controllers/JointPositionController
  joint: base

shoulder_controller:
  type: position_controllers/JointPositionController
  joint: shoulder

elbow_controller:
  type: position_controllers/JointPositionController
  joint: elbow

pitch_controller:
  type: position_controllers/JointPositionController
  joint: pitch

roll_controller:
  type: position_controllers/JointPositionController
  joint: roll

# Joint trajectory controller, all joints controller
trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base
    - shoulder
    - elbow
    - pitch
    - roll

gripper_controller:
  type: effort_controllers/JointEffortController
  joint: gripper

scorbot_control_hw:
  loop_frequency: 1000
  cycle_time_error_threshold: 0.002
  ethercat_iface: eno1

