scorbot:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60

  base_controller:
    type: position_controllers/JointPositionController
    joint: base

  shoulder_controller:
    type: position_controllers/JointPositionController
    joint: shoulder

  elbow_controller:
    type: position_controllers/JointPositionController
    joint: elbow

  pitch_controller:
    type: position_controllers/JointPositionController
    joint: pitch

  roll_controller:
    type: position_controllers/JointPositionController
    joint: roll

  gripper_controller:
    type: position_controllers/JointPositionController
    joint: gripper

  scorbot_control_hw:
    loop_frequency: 1000
    cycle_time_error_threshold: 0.002

